# stellar.toml for WiseMrMusa

[[CURRENCIES]]
code = "WiseMrMusa"
issuer = "GCO5MJSHMGRQRFUOARXXTT5AAN7WLRZZKXIXUIM3GYHWXKCGJ52YBGZV"

[TOML]
version = "1.0"

# Additional information
[DOCUMENTATION]
ORG_NAME = "WiseMrMusa"
ORG_URL = "https://www.wisemrmusa.com"

[[PRINCIPALS]]
name = "Musa AbdulKareem"
email = "wisemrmusa@gmail.com"
keybase = "wisemrmusa"
